install:
	wget -N http://twiki.org/p/pub/Plugins/TWikiDrawPlugin/TWikiDrawPlugin.zip
	unzip TWikiDrawPlugin.zip -d twiki
	cp twiki/pub/Plugins/TWikiDrawPlugin/* .
	rm -r twiki
	echo "*** TwikiDrawPlugin installed successfully"
uninstall:
	rm -f *.gif *.jar *.html *,v *.draw

