jsme:
	wget -N https://jsme-editor.github.io/downloads/JSME_2022-09-26.zip
	unzip JSME_2022-09-26.zip
	mv JSME_2022-09-26/jsme .
	rm -r JSME_2022-09-26

jme:
	wget http://www.molinspiration.com/jme/doc/JME.jar
